name: vnote
version: "2.3"
summary: Markdown note-taking app
description: |
    VNote is a note-taking application that
    knows programmers and Markdown better.
    It's designed to provide both powerful
    note management and pleasant Markdown
    experience.

confinement: devmode

apps:
    vnote:
        command: desktop-launch VNote

parts:
    vnote:
        source: https://github.com/tamlok/vnote.git
        plugin: qmake
        qt-version: qt5
        options:
            - CONFIG+=release
            - CONFIG+=c++11
            - CONFIG+=c99
            - QMAKE_CXX=g++-6
            - QMAKE_CC=gcc-6
            - QMAKE_CFLAGS+=-std=c99
            - ./VNote.pro
        build-packages:
            - build-essential
            - g++-6
            - gcc-6
            - qtbase5-dev
            - libqt5svg5-dev
            - libqt5webchannel5-dev
            - qt5-default
            - qtpositioning5-dev
            - qtwebengine5-dev
            - libxcb1-dev
            - libxcb-xkb-dev
            - libssl-dev
            - libgl1-mesa-dev
        stage-packages:
            - libqt5gui5
            - libqt5core5a
            - libqt5network5
            - libqt5printsupport5
            - libqt5webchannel5
            - libqt5webenginecore5
            - libqt5webenginewidgets5
            - libqt5widgets5
            - libqt5svg5
            - libxcb1
            - libxcb-xkb1
            - openssl
        after: [desktop-qt5]
